### ISSUE TITLE
i foud error 

### ISSUE THREAD

**Issue by thaigqsoft** [Pegascoin/go-Pegascoin#1]
root@PGC-COIN:/opt/go-Pegascoin# make gpg-cross
build/env.sh go run build/ci.go xgo -- --go=latest --dest=build/bin --targets=linux/386 -v ./cmd/gpg
unexpected directory layout:
	import path: _/opt/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	root: /opt/go-Pegascoin/build/_workspace/src
	dir: /opt/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/internal/build
	expand root: /opt/go-Pegascoin/build/_workspace/src
	expand dir: /opt/go-Pegascoin/internal/build
	separator: /
make: *** [gpg-linux-386] Error 1

on ubuntu 14.04 64bit

**Comment by bapparabi** [comment]
use 
make gpg
sudo make gpg

**Comment by cryptostevied** [comment]
Checking for required docker image karalabe/xgo-latest... found.
Cross compiling github.com/pegascoin/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/gpg...
Building locally github.com/pegascoin/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/gpg...
Compiling for linux/386...
github.com/ethereum/go-ethereum (download)
package github.com/ethereum/go-ethereum/logger: cannot find package "github.com/ethereum/go-ethereum/logger" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/logger (from $GOROOT)
	/go/src/github.com/ethereum/go-ethereum/logger (from $GOPATH)
	/ext-go/1/src/github.com/ethereum/go-ethereum/logger
	/ext-go/2/src/github.com/ethereum/go-ethereum/logger
	/ext-go/1/src/github.com/pegascoin/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/gpg/Godeps/_workspace/src/github.com/ethereum/go-ethereum/logger
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
	/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)
	/ext-go/1/src/github.com/ethereum/go-ethereum/logger/glog
	/ext-go/2/src/github.com/ethereum/go-ethereum/logger/glog
	/ext-go/1/src/github.com/pegascoin/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/gpg/Godeps/_workspace/src/github.com/ethereum/go-ethereum/logger/glog
package github.com/ethereum/go-ethereum/release: cannot find package "github.com/ethereum/go-ethereum/release" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/release (from $GOROOT)
	/go/src/github.com/ethereum/go-ethereum/release (from $GOPATH)
	/ext-go/1/src/github.com/ethereum/go-ethereum/release
	/ext-go/2/src/github.com/ethereum/go-ethereum/release
	/ext-go/1/src/github.com/pegascoin/go-Pegascoin/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/gpg/Godeps/_workspace/src/github.com/ethereum/go-ethereum/release
2018/02/14 21:47:39 Failed to cross compile package: exit status 1.
util.go:42: exit status 1
exit status 1
Makefile:43: recipe for target 'gpg-linux-386' failed
make: *** [gpg-linux-386] Error 1

**Comment by cryptostevied** [comment]
Go  you supply a linux-64 compiled build?

**Comment by thaigqsoft** [comment]
Yes linux-64 compiled build 
i use go version go1.6.2 linux/amd64  pass no error
thak

**Comment by cryptostevied** [comment]
I am doing the following command:

> go get github.com/pegascoin/go-Pegascoin/cmd/gpg

...and get the following response...

package github.com/ethereum/go-ethereum/logger: cannot find package "github.com/ethereum/go-ethereum/logger" in any of:
	/usr/lib/go/src/github.com/ethereum/go-ethereum/logger (from $GOROOT)
	/home/steve/go/src/github.com/ethereum/go-ethereum/logger (from $GOPATH)
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
	/usr/lib/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
	/home/steve/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)
package github.com/ethereum/go-ethereum/release: cannot find package "github.com/ethereum/go-ethereum/release" in any of:
	/usr/lib/go/src/github.com/ethereum/go-ethereum/release (from $GOROOT)
	/home/steve/go/src/github.com/ethereum/go-ethereum/release (from $GOPATH)

**Comment by cryptostevied** [comment]
I created a workaround to resolve the above and I'm left with the following:

go-pegascoin/cmd/gpg/main.go:38:2: use of internal package not allowed

That error could be because of my workaround or the remaining issue.
